version: "3.5"

services:
  reverseproxy:
    image: rinhabackend.reverseproxy
    build:
      context: .
      dockerfile: RinhaBackend.ReverseProxy/Dockerfile
    ports:
      - "9999:8080"
      - "443:443"
    depends_on:
      - api1
      - api2
      - postgres

  api1: &api
    image: rinhabackend.api
    hostname: api1
    build:
      context: .
      dockerfile: RinhaBackend.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:443"
      - "3001:8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "5002:443"
      - "3002:8080"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinhabacked