version: "3.5"

services:
  reverseproxy:
    image: marlonangeli/rinha-reverseproxy
    build:
      context: .
      dockerfile: RinhaBackend.ReverseProxy/Dockerfile
    ports:
      - "9999:8080"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - api1
      - api2
      - postgres
    deploy:
        resources:
            limits:
              cpus: "0.3"
              memory: "100MB"

  api1: &api
    image: marlonangeli/rinha-api
    hostname: api1
    build:
      context: .
      dockerfile: RinhaBackend.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:443"
      - "3001:8080"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "125MB"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "5002:443"
      - "3002:8080"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinhabacked