-- DDL

create table if not exists public."Clientes"
(
    "Id"           integer generated by default as identity
    constraint "PK_Clientes"
    primary key,
    "Limite"       double precision                          not null,
    "SaldoInicial" double precision                          not null,
    "Nome"         varchar(32) default ''::character varying not null
    );

alter table public."Clientes"
    owner to rinha;



create table if not exists public."Transacoes"
(
    "Id"        integer generated by default as identity
        constraint "PK_Transacoes"
            primary key,
    "Tipo"      char                     not null,
    "Valor"     double precision         not null,
    "Data"      timestamp with time zone not null,
    "Descricao" varchar(10)              not null,
    "ClienteId" integer                  not null
        constraint "FK_Transacoes_Clientes_ClienteId"
            references public."Clientes"
            on delete cascade
);

alter table public."Transacoes"
    owner to rinha;

create index "IX_Transacoes_ClienteId"
    on public."Transacoes" ("ClienteId");


-- DML

insert into
    public."Clientes" ("Nome", "Limite", "SaldoInicial")
values
    ('o barato sai caro', 1000 * 100, 0),
    ('zan corp ltda', 800 * 100, 0),
    ('les cruders', 10000 * 100, 0),
    ('padaria joia de cocaia', 100000 * 100, 0),
    ('kid mais', 5000 * 100, 0);
